name: ml-latest
channels:
    - pyg
    - pytorch
    - conda-forge
dependencies:
    - python=3.8
    - numpy
    - uproot
    - tensorflow
    - xrootd
    - scikit-learn
    - matplotlib
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - pyg
    - mplhep
    - pydot
    - graphviz
    - autopep8
    - tqdm
    - black
    - pip
    - pip:
      - jupyter-book
      - git+https://github.com/fastmachinelearning/hls4ml.git@main#egg=hls4ml[profiling]
      - qkeras==0.9.0
