name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --no-cache-dir -r book/requirements.txt
        python -m pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
        python -m pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.0+cpu.html
        python -m pip install git+https://github.com/pyg-team/pytorch_geometric.git
        python -m pip list

    - name: Build the book
      shell: bash -l {0}
      run: |
        jupyter-book build book

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/_build/html